command to add new member
kamranahmedse/makers.ae pull request #8
Opened 2020-11-03 12:26 UTC by abidhkm

Command for adding a new member to the member list.

2020-11-03 16:55 UTC, kamranahmedse requested changes
Thanks @abidhkm just few minor comments :)

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +async function addMember() {
No need for this separate function, let's put the logic inside the same command body

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +    .then(async (answer: Answer) => {
Don't mix `await` and `.then`, we can just do

```typescript
const answer: Answer = await inquirer.prompt(..)
```

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +const MEMBERS_DIR = "./data/members";
Use camel case for the constants and also for the values use `process.cwd()`

```typescript
const avatarsDir = path.join(process.cwd(), './public/avatars');
const membersDir = path.join(process.cwd(), './public/members');
```

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +    });
Just use `fs.writeFileSync(path.join(avatarsDir, fileName), buffer)` no need for callback

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +  }
Make the function just return the `fileName` or `false` and put the check in the caller and exit with error if the image couldn't be saved.

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +      const directory = `${MEMBERS_DIR}/${answer.username}`;
Always use `path.join` when joining paths
```suggestion
      const memberDir = path.join(membersDir, answer.username);
```

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +      );
Just use `fs.writeFileSync`, use `path.join` to combine directory path with the filename and format the JSON

```typescript
fs.writeFileSync(memberProfilePath, JSON.stringify(null, true, 2))
```

2020-11-03 16:55 UTC, kamranahmedse commented on cmd/add-member.cmd.ts
> +      });
Same here, `writeFileSync`

2020-11-04 16:46 UTC, abidhkm commented
sure, addressing the comments.

2020-11-05 17:50 UTC, abidhkm commented
comments are addressed, please review.

2020-11-05 18:17 UTC, kamranahmedse approved these changes
Thanks @abidhkm

2020-11-05 18:17 UTC, merged